// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Task.Api.Data;

#nullable disable

namespace Task.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230721055822_First-Migration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Task.Api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Percent")
                        .HasColumnType("integer");

                    b.Property<int>("RangeFrom")
                        .HasColumnType("integer");

                    b.Property<int>("RangeTo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ab6dbd8-da7d-40ad-86b4-8a002eb3994f"),
                            CategoryName = "smartphone",
                            Percent = 3,
                            RangeFrom = 3,
                            RangeTo = 9
                        },
                        new
                        {
                            Id = new Guid("f83f47d3-b583-4e6e-af03-116bf735a172"),
                            CategoryName = "computer",
                            Percent = 4,
                            RangeFrom = 3,
                            RangeTo = 12
                        },
                        new
                        {
                            Id = new Guid("68131fd5-5d02-4d7b-8768-57087a204e67"),
                            CategoryName = "tv",
                            Percent = 5,
                            RangeFrom = 3,
                            RangeTo = 18
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
